[workspace]
members = ["plugin"]

[package]
name = "extism-demo"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib"]

[dependencies]
anyhow = "1.0.71"
extism-pdk = "0.3.2"
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
extism = "0.4.0"
